export default {
  title: 'Students',
  description:
    'Super Admins create and export students. Department Admins import and manage status.',
  endpoint: '/students',
  columns: [
    ['student_id', 'Seat Number'],
    ['name', 'Name'],
    ['father_name', 'Father Name'],
    ['enrollment_no', 'Enrollment'],
    ['batch_name', 'Batch'],
    ['admission_year', 'Admission Year'],
    ['semester', 'Semester'],
    ['section_name', 'Section'],
  ],
  fields: [
    { name: 'department_id', label: 'Department ID', required: true },
    { name: 'batch_id', label: 'Batch ID', required: true },
    { name: 'student_id', label: 'Seat Number', required: true },
    { name: 'enrollment_no', label: 'Enrollment no.', required: true },
    { name: 'name', label: 'Full name', required: true },
    { name: 'father_name', label: 'Father name' },
    { name: 'admission_year', label: 'Admission Year' },
    { name: 'email', label: 'Email' },
    { name: 'phone', label: 'Phone' },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'active', label: 'Active' },
        { value: 'disabled', label: 'Inactive' },
      ],
    },
  ],
  create: true,
  createRoles: ['super_admin'],
  edit: true,
  editRoles: ['super_admin', 'admin'],
  remove: true,
  removeRoles: ['super_admin'],
  templateEndpoint: '/students/import/template',
  templateRoles: ['super_admin'],
  importEndpoint: '/students/import',
  importRoles: ['super_admin'],
  searchable: true,
  searchPlaceholder: 'Search students by name, father name, seat number, enrollment, or email',
  paginated: true,
  filters: ['department', 'semester'],
  detail: true,
};
