export default {
  title: 'Teachers',
  description: 'Browse all teachers. Super Admins manage teacher accounts.',
  endpoint: '/teachers',
  searchable: true,
  searchPlaceholder: 'Search teachers by name, login ID, or email',
  columns: [
    ['name', 'Name'],
    ['login_id', 'User Name'],
    ['email', 'Email'],
  ],
  adminColumns: [
    ['name', 'Name'],
    ['email', 'Email'],
    ['status', 'Status'],
  ],
  fields: [
    { name: 'name', label: 'Full name *', required: true },
    { name: 'login_id', label: 'User Name *', required: true },
    { name: 'email', label: 'Email *', required: true },
    { name: 'phone', label: 'Phone *', required: true },
    { name: 'password', label: 'Password (optional)', type: 'password' },
  ],
  create: true,
  createRoles: ['super_admin'],
  edit: true,
  editRoles: ['super_admin'],
  templateEndpoint: '/teachers/import/template',
  templateRoles: ['super_admin'],
  exportEndpoint: '/teachers/export',
  exportRoles: ['super_admin'],
  importEndpoint: '/teachers/import',
  importRoles: ['super_admin'],
};